from enum import Enum


class TipoResultadoInicial(str, Enum):
    VENCEDOR = "VENCEDOR"
    EMPATE = "EMPATE"
    FRACASSADO = "FRACASSADO"
    DESERTO = "DESERTO"

class StatusPosPregao(str, Enum):
    # Estado inicial após disputa
    EM_CONFERENCIA = "EM_CONFERENCIA"

    # Fluxo de ganho
    ARREMATANTE = "ARREMATANTE"
    EM_HABILITACAO = "EM_HABILITACAO"
    HABILITADO = "HABILITADO"
    ADJUDICADO = "ADJUDICADO"
    CONTRATO_RECEBIDO = "CONTRATO_RECEBIDO"
    EMPENHO_RECEBIDO = "EMPENHO_RECEBIDO"

    # Fluxo de perda monitorável
    PERDIDO_MONITORAVEL = "PERDIDO_MONITORAVEL"
    AGUARDANDO_QUEDA = "AGUARDANDO_QUEDA"
    CONVOCADO = "CONVOCADO"

    # Final
    ENCERRADO = "ENCERRADO"
